# Generated by Django 3.2.4 on 2021-07-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sneakerhead',
            new_name='Sneaker',
        ),
    ]
