# Generated by Django 3.2.4 on 2021-07-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
